env: "local" # local, dev, prod
postgresql:
  host: db
  port: 5432
  username: postgres
  password: postgres
  database: postgres
http_server:
  address: :8080
  timeout: 4s
  idle_timeout: 60s
jwt:
  secret: $3cr3t
  access_token_ttl: 5m
  refresh_token_ttl: 720h
smtp:
  host: smtp.mail.ru
  port: 465
  username: your_email@mail.ru
  password: email_app_password